
const RES_OK = 200;
const RES_BAD_REQUEST = 400;
const RES_UNAUTHORIZED = 401;
const RES_FORBIDDEN = 403;
const RES_NOT_FOUND = 404;

export { RES_OK, RES_BAD_REQUEST, RES_UNAUTHORIZED, RES_FORBIDDEN, RES_NOT_FOUND };